---
# tasks file for git
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
  - name: Install git
    apt:
      name: git
    state: present
